root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: 'detect'
env:
  browser: true
  amd: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended # must be latest
plugins:
  - simple-import-sort
  - react-hooks
  - '@typescript-eslint'
  - prettier
globals:
  JSX: readonly
rules:
  prettier/prettier:
    - error
    - {}
    - usePrettierrc: true
  react/react-in-jsx-scope: 'off'
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars': error
  simple-import-sort/imports:
    - error
    - groups:
        - - '^react'
          - "^@?\\w"
        - - '^(@|components)(/.*|$)'
        - - "^\\u0000"
        - - "^\\.\\.(?!/?$)"
          - "^\\.\\./?$"
        - - "^\\./(?=.*/)(?!/?$)"
          - "^\\.(?!/?$)"
          - "^\\./?$"
        - - "^.+\\.?(css)$"
  simple-import-sort/exports: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
    - warn
    - additionalHooks: (useRecoilCallback|useRecoilTransaction_UNSTABLE)
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - hrefLeft
        - hrefRight
      aspects:
        - invalidHref
        - preferButton
